name: Intermediate environment variables
on:
  push:
    paths:
      - '.github/workflows/intermediate-environment-variables.yml'
jobs:
  print:
    runs-on: ubuntu-latest
    env:
      ACTOR: handson-test # コンテキストの値を環境変数へセット
    steps:
      - run: echo "${ACTOR}"     # 環境変数経由でコンテキストのプロパティを参照
